### ISSUE TITLE
[Docs] Add usage example with gamera/hump.camera

### ISSUE THREAD

**Issue by alexmozaidze** [Vovkiv/resolution_solution#18]
It would be appreciated if you documented on how to make this library work with [gamera](https://github.com/kikito/gamera) or [hump.camera](https://hump.readthedocs.io/en/latest/camera.html). There is a [snippet of code](https://love2d.org/forums/viewtopic.php?p=248108&hilit=camera#p248108) on the forums that shows how to do this, but it didn't seem to work with the latest version of this library, to be specific, setting camera position doesn't work.

**Comment by Vovkiv** [comment]
Oh, I didn't noticed new issues, hah.
Yes, there will be some snippets how you can implement cameras, in examples folder and in documentation:
https://github.com/Vovkiv/resolution_solution/tree/v3000_rewrite

**Comment by Vovkiv** [comment]
@alexmozaidze here, gamera example: https://github.com/Vovkiv/resolution_solution/tree/v3000_rewrite/examples/gamera
If you have questions or want to provide feedback, write new comment on this issue.
(Keep in mind, that this example done for v3000 version, which quite drastically changed compared to older versions.)
HUMP goes next.

**Comment by alexmozaidze** [comment]
Thanks for taking your time helping, unfortunately, I currently can't check out the example due to my PC's monitor being broken. Looking forward to try v3000 once I get my monitor fixed! Thanks for making such a cool library!

**Comment by Vovkiv** [comment]
Yay!
Also keep in mind, this v3000 is still WIP, so not everything done yet (like documentation, or examples) but library itself should be already 100% usable without any issues.
And I might push it in near future(TM), so I can finally get over it.

**Comment by Vovkiv** [comment]
[6d1a071](https://github.com/Vovkiv/resolution_solution/commit/6d1a071e13d1b44eb0d2de5dff657f86c383090e)
Finished HUMP camera example.
For now, issue will be closed, but if you need to provide feedback at some point, re-open issue.
